# Generated by Django 4.0.4 on 2022-05-25 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CaraPakai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('richText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingredients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=100)),
                ('richText', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ObatDiet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('caraPakai', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mydiet.carapakai')),
                ('ingredients', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='mydiet.ingredients')),
            ],
        ),
    ]
