# Generated by Django 4.0.4 on 2022-06-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mydiet', '0002_obatdiet_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(null=True, upload_to='article/')),
                ('link', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('harga', models.IntegerField()),
                ('rating', models.FloatField()),
                ('deskripsi', models.TextField()),
                ('caraPakai', models.TextField()),
                ('ingredients', models.TextField()),
                ('image', models.ImageField(null=True, upload_to='products/')),
            ],
        ),
        migrations.RemoveField(
            model_name='obatdiet',
            name='caraPakai',
        ),
        migrations.RemoveField(
            model_name='obatdiet',
            name='ingredients',
        ),
        migrations.DeleteModel(
            name='CaraPakai',
        ),
        migrations.DeleteModel(
            name='Ingredients',
        ),
        migrations.DeleteModel(
            name='ObatDiet',
        ),
    ]
